version: "3"

services:
  ui:
    build:
      context: ui
    ports:
      - "80:80"
    volumes:
      - ./ui/src/client/public:/var/www/html

  api:
    build: .
    ports:
      - "8080:8080"
    command: ["api"]
    environment:
      - M8S_UI_MOCK=true